spring:
  datasource:
     url: jdbc:mysql://localhost:3306/realvega?verifyServerCertificate=false&useSSL=true
     username: realvega
     password: realvega
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: create-drop
server:
  port: 8080

---
spring:
  profiles: container
  datasource:
     url: jdbc:mysql://springdbex:3306/realvega?verifyServerCertificate=false&useSSL=true
     username: realvega
     password: realvega
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: create-drop
server:
  port: 8080

---
spring:
  profiles: remote
  datasource:
     url: jdbc:mysql://springdbex:3306/realvega?verifyServerCertificate=false&useSSL=true
     username: realvega
     password: realvega
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: create-drop
server:
  port: 8080
