name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: apt update
      run: sudo su && apt-get update && exit
    
    - name: apt install kubectl
      run: sudo su && apt-get install -y kubectl && exit
    
    - name: k version
      run: kubectl version
