name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: apt update
      run: apt-get update
    
    - name: apt install kubectl
      run: apt-get install -y kubectl
    
    - name: k version
      run: kubectl version
